name = "SplitOrderedCollections"
uuid = "4b700b29-7da4-4670-af42-5a9783ffd6e0"
authors = ["April Herwig <aprillherwig@gmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SplittablesBase = "171d559e-b47b-412a-8079-5efa626c420e"

[compat]
julia = "1"
OrderedCollections = "1.1.0"
SplittablesBase = "0.1.2"
